# Generated by Django 4.0.5 on 2022-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentgroup_student_birthday_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='students_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество студентов'),
        ),
    ]
